// flow-typed signature: b328e0fccf99f65c7bedc9b0f877d485
// flow-typed version: <<STUB>>/decompress_v^4.2.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'decompress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'decompress' {
  declare type FilterMethod = (file: DecompressedFile) => boolean;

  declare type DecompressOptions = {
    filter?: FilterMethod,
  };

  declare type DecompressOutput = Array<DecompressedFile>;

  declare type DecompressedFile = {
    data: Buffer,
    path: string,
  };

  declare type Decompress =
    | ((
        localPath: string,
        options?: DecompressOptions,
        _: void,
      ) => Promise<DecompressOutput>)
    | ((
        localPath: string,
        destPath: string,
        options?: DecompressOptions,
      ) => Promise<DecompressOutput>);
  declare export default Decompress;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'decompress/index' {
  declare module.exports: $Exports<'decompress'>;
}
declare module 'decompress/index.js' {
  declare module.exports: $Exports<'decompress'>;
}
