// flow-typed signature: 7d7743293687288adf3d5fc8a427d2d1
// flow-typed version: <<STUB>>/jest-plugin-fs_v^2.9.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-plugin-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-plugin-fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-plugin-fs/build/fs' {
  declare module.exports: any;
}

declare module 'jest-plugin-fs/mock' {
  declare module.exports: any;
}

declare module 'jest-plugin-fs/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-plugin-fs/build/fs.js' {
  declare module.exports: $Exports<'jest-plugin-fs/build/fs'>;
}
declare module 'jest-plugin-fs/mock.js' {
  declare module.exports: $Exports<'jest-plugin-fs/mock'>;
}
declare module 'jest-plugin-fs/setup.js' {
  declare module.exports: $Exports<'jest-plugin-fs/setup'>;
}
