// flow-typed signature: 5a3b4f38422a00707da0912349da73b1
// flow-typed version: <<STUB>>/modern-rcon_v^1.0.3/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'modern-rcon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'modern-rcon' {
  declare export default class ModernRcon {
    constructor(
      host: string,
      port?: number,
      password: string,
      timeout?: number,
    ): this;

    connect(): Promise<void>;
    disconnect(): Promise<void>;

    send(command: string): Promise<string>;
  }
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'modern-rcon/rcon' {
  declare module.exports: $Exports<'modern-rcon'>;
}

// Filename aliases
declare module 'modern-rcon/rcon.js' {
  declare module.exports: $Exports<'modern-rcon/rcon'>;
}
