// flow-typed signature: 05088e1cec87b36177fbd5015dbe610a
// flow-typed version: <<STUB>>/ps-node_v^0.1.6/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ps-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "ps-node" {
  declare export type LookupQuery = {
    pid?: string | Array<string>,
    command?: string | RegExp,
    arguments?: string | RegExp
  };
  declare export type LookupResult = {
    pid: string,
    command: string,
    arguments: string
  };
  declare export type LookupResultList = Array<LookupResult>;
  declare export function lookup(
    query: LookupQuery,
    callback: (err: ?Error, result: ?LookupResultList) => void
  ): void;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "ps-node/lib/index" {
  declare module.exports: $Exports<"ps-node">;
}

// Filename aliases
declare module "ps-node/index" {
  declare module.exports: $Exports<"ps-node">;
}
declare module "ps-node/index.js" {
  declare module.exports: $Exports<"ps-node">;
}
declare module "ps-node/lib/index.js" {
  declare module.exports: $Exports<"ps-node/lib/index">;
}
