// flow-typed signature: 46ceed626b99328126aa31861b893235
// flow-typed version: <<STUB>>/tail_v^2.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tail'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tail' {
  declare export class Tail {
    constructor(path: string): this;
    watch(): void;
    unwatch(): void;
    on(event: 'line', lineCallback: (string) => void): this;
    on(event: 'error', errorCallback: (Error) => void): this;
    off(event: 'line', lineCallback: (string) => void): this;
    off(event: 'error', errorCallback: (Error) => void): this;
  }
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tail/lib/tail' {
  declare module.exports: $Exports<'tail'>;
}

// Filename aliases
declare module 'tail/lib/tail.js' {
  declare module.exports: $Exports<'tail/lib/tail'>;
}
