// flow-typed signature: a0ad40f5131e9f84dec0f3d644236a56
// flow-typed version: <<STUB>>/yazl_v^2.4.3/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yazl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yazl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'yazl/index' {
  declare module.exports: $Exports<'yazl'>;
}
declare module 'yazl/index.js' {
  declare module.exports: $Exports<'yazl'>;
}
